version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - FINNHUB_KEY=${FINNHUB_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
    ports:
      - "8000:8000"
    command: python src/main.py

  # Add Redis for caching and message queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Add PostgreSQL for data storage
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-trading}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: 